[package]
name = "perchbot"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
once_cell = "1.21.3"
regex = "1.12.2"
serenity = "0.12.2"
tokio = { version = "1.38.1", features = ["full"] }
